In [14]:
# Task:
# Create a 4x5 array of numbers from 1 to 20 using reshape.
# Slice the middle 2x3 block.

import numpy as np
arr = np.arange(20)
print(f"Array in flattened form :{arr}")
reshaped = arr.reshape(4,5)
print(f"Array in 4 x 5 form : \n{reshaped}")
print(f"Dimensions of the Array is : {reshaped.ndim}")
block = reshaped[1:3,0:4]
print(f"The middle 2x3 block of the above array :\n{block}")

Array in flattened form :[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
Array in 4 x 5 form : 
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
Dimensions of the Array is : 2
The middle 2x3 block of the above array :
[[ 5  6  7  8]
 [10 11 12 13]]
