##Creating Arrrays from Scratch

In [72]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5]) 
print(arr)

[1 2 3 4 5]


In [73]:
#zeros array
zeros = np.zeros((3,3))
print(f"Zeroa Array are :\n{zeros}")

Zeroa Array are :
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [74]:
#ones Array
ones = np.ones((4,5))
print(f"Ones Array are :\n{ones}")

Ones Array are :
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [75]:
#Twos Array or also for any constant value
twos = np.full((3,3,), 2)
print(f"Twos Array are :\n{twos}")

Twos Array are :
[[2 2 2]
 [2 2 2]
 [2 2 2]]


In [76]:
import numpy as np

random = np.random.randint(0, 100, size=(2, 10))  # Random integers from 0 to 99
print(f"Random integers:\n{random}")


Random integers:
[[74 48 96 83  2 68 62 85 43 15]
 [91 56 31 75 80 70  5 64  0 16]]


In [77]:
#sequencw Array
sequence = np.arange(0,20,2)
print(f"Sequence Array are :\n{sequence}")

Sequence Array are :
[ 0  2  4  6  8 10 12 14 16 18]


##Vector, Matrix and Tensor

In [78]:
#vectors are flat arrays and 1D arrays
vectors = np.array([1,2,3,4,5,6,6,7,8,9,10])
print("flat array or vector is :\n", vectors)

flat array or vector is :
 [ 1  2  3  4  5  6  6  7  8  9 10]


In [79]:
#Matrix can be 2D arrays
matrix = np.array([[1,2,3],[4,5,6]])
print(f"Matrix is :\n{matrix}")
print(f"Shape of Matrix is :\n{matrix.shape}")
print(f"Size of Matrix is :\n{matrix.size}")
print(f"Dimension of Matrix is :\n{matrix.ndim}")
print(f"Data type of Matrix is :\n{matrix.dtype}")

Matrix is :
[[1 2 3]
 [4 5 6]]
Shape of Matrix is :
(2, 3)
Size of Matrix is :
6
Dimension of Matrix is :
2
Data type of Matrix is :
int64


In [80]:
#Tensor can be 3D arrays or more than 3D upto 32 dimensions
tensor = np.array([[[1,2,3],[3,2,1,],[5,6,7]],[[8,7,6],[4,5,6],[1,2,3]]])
print(f"Tensor array is : {tensor}")
print(f"Dimension of the Tensor array is : {tensor}")


Tensor array is : [[[1 2 3]
  [3 2 1]
  [5 6 7]]

 [[8 7 6]
  [4 5 6]
  [1 2 3]]]
Dimension of the Tensor array is : [[[1 2 3]
  [3 2 1]
  [5 6 7]]

 [[8 7 6]
  [4 5 6]
  [1 2 3]]]


##Array Properties 

In [81]:
arr = np.array([[1,2,3],[4,5,6]])
#shape property show us the number of rows and coloumn
print(f"Shape of the array is :{arr.shape}")
#ndim property show us the dimensions 
print(f"Dimensions of the Array is : {arr.ndim}")
#Size of the Array is 
print(f"Size of the Array is : {arr.size}")
#Data Type of the array is :
print(f"Data type of the array is : {arr.dtype}")
#Type method will show us the type of the array
print(type(arr))

Shape of the array is :(2, 3)
Dimensions of the Array is : 2
Size of the Array is : 6
Data type of the array is : int64
<class 'numpy.ndarray'>


##Arrays Shapping and Reshapping

In [82]:
arr = np.arange(12)
print(arr)
#method reshape is used to convert these array into rows and coloumns
print(f"Array in the form of rows and coloumns : \n{arr.reshape(3,4)}")
#method flattened is used to convert the rows and coloumns into flattened array
print(f"Flattened array is : {arr.flatten()}")
#ravel method is also used to convert the dimensional array into flattened
print(f"Convert the array into flattened by ravel method : {arr.ravel()} ")
#but the difference between the ravel() and flatten() is ravel effect the original but flatten make copy

[ 0  1  2  3  4  5  6  7  8  9 10 11]
Array in the form of rows and coloumns : 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened array is : [ 0  1  2  3  4  5  6  7  8  9 10 11]
Convert the array into flattened by ravel method : [ 0  1  2  3  4  5  6  7  8  9 10 11] 


In [83]:
##Transpose of the array using methods
arr = np.array([[1,2,3],[5,4,3]])
transpose_arr = arr.T
print(f"Original Array is : \n{arr}")
print(f"Rows and Coloumn of the original array is :\n{arr.shape}")
print(f"Transpose of the Array is : \n{transpose_arr}")
print(f"Rows and Coloumn of the Transpose array is :\n{transpose_arr.shape}")

Original Array is : 
[[1 2 3]
 [5 4 3]]
Rows and Coloumn of the original array is :
(2, 3)
Transpose of the Array is : 
[[1 5]
 [2 4]
 [3 3]]
Rows and Coloumn of the Transpose array is :
(3, 2)
