###Numpy Arrays operation

In [4]:
import numpy as np

In [5]:
#Basic Slicing
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr[:])  #will print all elements present in the array
print(arr[3:]) #will print all elements after index 3
print(arr[:4]) #wiill print all elements from start to index 4 but not included index 4 
print(arr[-3]) #will print element no subtract from the total index
print(arr[-7:-2]) #will print elements from index 10 - 7 to index 10 - 2

[ 1  2  3  4  5  6  7  8  9 10]
[ 4  5  6  7  8  9 10]
[1 2 3 4]
8
[4 5 6 7 8]


###Slicing on 2D arrays

In [6]:
arr_2D = np.array([[1,2,3],[4,5,6]])
print(arr_2D[1,1]) #will print the element no 2 in the row 2
print(arr_2D[:,1]) #will print all the elements 2's of all the rows
print(arr_2D[0:,]) #will print all the elements of rows from index 0 to onwords
print(arr_2D[1]) #will print all the elements of row no 2

5
[2 5]
[[1 2 3]
 [4 5 6]]
[4 5 6]


###Sorting on Arrays

In [7]:
unsorted_array = np.array([1,3,4,5,6,7,5,43,89,8,643,23,45,67])
sorted = np.sort(unsorted_array)
print(f"Unsorted array :{unsorted_array}")
print(f"Sorted array :{sorted}")

Unsorted array :[  1   3   4   5   6   7   5  43  89   8 643  23  45  67]
Sorted array :[  1   3   4   5   5   6   7   8  23  43  45  67  89 643]


###Sorting on 2D Arrays

In [8]:
unsorted_arr = np.array([[1,3,4,2],[6,7,8,5],[2,1,3,5]])
sorted_arr = np.sort(unsorted_arr , axis=0)
print(f"unsorted Array is :\n{unsorted_arr}")
print(f"Array after sorted in axis of coloumns : \n{sorted_arr}")

print("\n")

unsorted_arr = np.array([[1,3,4,2],[6,7,8,5],[2,1,3,5]])
sorted_arr = np.sort(unsorted_arr , axis=1)
print(f"unsorted Array is :\n{unsorted_arr}")
print(f"Array after sorted in the axis of rows : \n{sorted_arr}")

unsorted Array is :
[[1 3 4 2]
 [6 7 8 5]
 [2 1 3 5]]
Array after sorted in axis of coloumns : 
[[1 1 3 2]
 [2 3 4 5]
 [6 7 8 5]]


unsorted Array is :
[[1 3 4 2]
 [6 7 8 5]
 [2 1 3 5]]
Array after sorted in the axis of rows : 
[[1 2 3 4]
 [5 6 7 8]
 [1 2 3 5]]


###Filtering Arrays

In [9]:
#It's like applying conditions on arrays such as following
arr = np.array([1,2,3,4,5,6,7,8,9,10])
even_numbers = arr[arr%2==0]
print(f"Even numbers are {even_numbers}")

odd_numbers = arr[arr%2!=0]
print(f"Odd numbers are {odd_numbers}")

Even numbers are [ 2  4  6  8 10]
Odd numbers are [1 3 5 7 9]


###Filter with Mask method

In [10]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
mask1 = arr > 5
mask2 = arr % 2 == 0
print(f"Numbers greater than are given as {arr[mask1]}")
print(f"Even numbers are {arr[mask2]}")

Numbers greater than are given as [ 6  7  8  9 10]
Even numbers are [ 2  4  6  8 10]


###Fancy Indexing vs np.where()

In [ ]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
indices = [0,2,4]#it means print the numbers at index 0 , 2 and 4
print(numbers[indices])

where_result = np.where(numbers>5)#it also work as a condition
print(where_result)
print(f"NP where numbers {numbers[where_result]}" )

[1 3 5]
(array([5, 6, 7, 8, 9]),)
NP where numbers [ 6  7  8  9 10]


###Conditionals Arrays

In [ ]:
nums = np.array([1,2,3,4,5,6,7,8,9,10])
conditional_array = np.where(nums > 5 , nums*2 , "False")
print(conditional_array)

#or


['False' 'False' 'False' 'False' 'False' '12' '14' '16' '18' '20']
False


###Adding and Removing data to Arrrays

In [23]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])
union = np.concatenate([arr1, arr2])
print(f"Union of the array1 and array 2 is : {union}")

Union of the array1 and array 2 is : [ 1  2  3  4  5  6  7  8  9 10]


###Arrays Compatibility

In [ ]:
a = np.array([1,2,3,4,5])
b = np.array([5,3,3,2,2,6])
print(f"Shape Compatibility : {a.shape == b.shape}")#if the condition is true it print true otherwise it print false

Shape Compatibility : False


###Added new rows to original array

In [39]:
original_array = np.array([[1,2,3,4],[4,3,2,1]])
new_row = np.array([8,9,7,6])
with_new_row = np.vstack((original_array,new_row))
print(f"Row is added horizantily \n{with_new_row}")


new_col = np.array([[11,22],[33,44]])
with_new_col = np.hstack((original_array, new_col))
print(f"Coloumns is added vertically : \n{with_new_col}")



Row is added horizantily 
[[1 2 3 4]
 [4 3 2 1]
 [8 9 7 6]]
Coloumns is added vertically : 
[[ 1  2  3  4 11 22]
 [ 4  3  2  1 33 44]]


###Delete an Array

In [ ]:
arr = np.array([1,2,3,4,5])
deleted = np.delete(arr,3) #it will delete number at index 3 in array
print(deleted)

[1 2 3 5]
